<?php

return [

	/*
	|--------------------------------------------------------------------------
	| Composer File Template
	|--------------------------------------------------------------------------
	|
	| Here is the config for composer.json file, generated by this package
	|
	*/

	'composer' => [
		'vendor' => 'Pixel',
		'author' => [
			'name' => 'Ivan Suazo',
			'email' => 'ivan@pixel.hn',
		],
	],

	/*
	|--------------------------------------------------------------------------
	| Caching
	|--------------------------------------------------------------------------
	|
	| Here is the config for setting up caching feature.
	|
	*/
	
	'cache' => [
		'enabled' => false,
		'key' => 'laravel-modules',
		'lifetime' => 60,
	],

	/*
	|--------------------------------------------------------------------------
	| Activators
	|--------------------------------------------------------------------------
	|
	| You can define new types of activators here, file, database etc.
	| The file activator will store the activation status in storage/installed_modules
	*/

	'activator' => 'file',
];
